import type { Barbershop, Review, Booking, Employee, PlatformStats } from "./types"

export const mockBarbershops: Barbershop[] = [
  {
    id: "1",
    name: "Barbearia Clássica",
    description: "Tradição e estilo desde 1985. Especialistas em cortes clássicos e modernos.",
    ownerId: "barber1",
    address: "Av. Barão do Rio Branco, 2234 - Centro, Juiz de Fora - MG",
    latitude: -21.7642,
    longitude: -43.3502,
    phone: "(32) 98765-4321",
    images: ["/classic-barbershop.png"],
    rating: 4.8,
    reviewCount: 127,
    services: [
      { id: "s1", name: "Corte Masculino", description: "Corte completo com acabamento", price: 50, duration: 45 },
      { id: "s2", name: "Barba", description: "Aparar e modelar barba", price: 35, duration: 30 },
      { id: "s3", name: "Corte + Barba", description: "Combo completo", price: 75, duration: 60 },
    ],
    workingHours: {
      monday: [{ start: "09:00", end: "19:00" }],
      tuesday: [{ start: "09:00", end: "19:00" }],
      wednesday: [{ start: "09:00", end: "19:00" }],
      thursday: [{ start: "09:00", end: "19:00" }],
      friday: [{ start: "09:00", end: "20:00" }],
      saturday: [{ start: "08:00", end: "18:00" }],
      sunday: [],
    },
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Urban Cuts",
    description: "Estilo urbano e contemporâneo. Ambiente moderno e descontraído.",
    ownerId: "barber2",
    address: "Rua Halfeld, 916 - Centro, Juiz de Fora - MG",
    latitude: -21.7587,
    longitude: -43.3489,
    phone: "(32) 97654-3210",
    images: ["/modern-urban-barbershop.jpg"],
    rating: 4.9,
    reviewCount: 203,
    services: [
      { id: "s4", name: "Corte Moderno", description: "Cortes atuais e estilosos", price: 60, duration: 50 },
      { id: "s5", name: "Degradê", description: "Degradê profissional", price: 55, duration: 45 },
      { id: "s6", name: "Platinado", description: "Descoloração completa", price: 150, duration: 120 },
    ],
    workingHours: {
      monday: [{ start: "10:00", end: "20:00" }],
      tuesday: [{ start: "10:00", end: "20:00" }],
      wednesday: [{ start: "10:00", end: "20:00" }],
      thursday: [{ start: "10:00", end: "20:00" }],
      friday: [{ start: "10:00", end: "21:00" }],
      saturday: [{ start: "09:00", end: "19:00" }],
      sunday: [{ start: "10:00", end: "16:00" }],
    },
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    name: "Rei do Corte",
    description: "Atendimento premium com profissionais experientes.",
    ownerId: "barber3",
    address: "Av. Independência, 3245 - Bairro Industrial, Juiz de Fora - MG",
    latitude: -21.7712,
    longitude: -43.3621,
    phone: "(32) 96543-2109",
    images: ["/premium-barbershop-luxury.jpg"],
    rating: 4.7,
    reviewCount: 89,
    services: [
      { id: "s7", name: "Corte Premium", description: "Corte com lavagem e finalização", price: 80, duration: 60 },
      { id: "s8", name: "Barba Premium", description: "Barba com toalha quente", price: 50, duration: 40 },
      { id: "s9", name: "Pacote Completo", description: "Corte + Barba + Sobrancelha", price: 120, duration: 90 },
    ],
    workingHours: {
      monday: [{ start: "09:00", end: "18:00" }],
      tuesday: [{ start: "09:00", end: "18:00" }],
      wednesday: [{ start: "09:00", end: "18:00" }],
      thursday: [{ start: "09:00", end: "18:00" }],
      friday: [{ start: "09:00", end: "19:00" }],
      saturday: [{ start: "08:00", end: "17:00" }],
      sunday: [],
    },
    createdAt: new Date("2024-03-10"),
  },
]

export const mockReviews: Review[] = [
  {
    id: "r1",
    clientId: "client1",
    clientName: "João Silva",
    clientAvatar: "/placeholder.svg?height=40&width=40",
    barbershopId: "1",
    rating: 5,
    comment: "Excelente atendimento! Profissionais muito qualificados e ambiente agradável.",
    createdAt: new Date("2024-10-01"),
  },
  {
    id: "r2",
    clientId: "client2",
    clientName: "Pedro Santos",
    clientAvatar: "/placeholder.svg?height=40&width=40",
    barbershopId: "1",
    rating: 5,
    comment: "Melhor barbearia da região. Sempre saio satisfeito!",
    createdAt: new Date("2024-09-28"),
  },
  {
    id: "r3",
    clientId: "client3",
    clientName: "Carlos Oliveira",
    clientAvatar: "/placeholder.svg?height=40&width=40",
    barbershopId: "1",
    rating: 4,
    comment: "Muito bom! Só achei um pouco caro, mas vale a pena.",
    createdAt: new Date("2024-09-25"),
  },
  {
    id: "r4",
    clientId: "client4",
    clientName: "Lucas Ferreira",
    clientAvatar: "/placeholder.svg?height=40&width=40",
    barbershopId: "2",
    rating: 5,
    comment: "Ambiente moderno e corte impecável. Recomendo!",
    createdAt: new Date("2024-10-05"),
  },
  {
    id: "r5",
    clientId: "client5",
    clientName: "Rafael Costa",
    clientAvatar: "/placeholder.svg?height=40&width=40",
    barbershopId: "2",
    rating: 5,
    comment: "Atendimento nota 10! Voltarei com certeza.",
    createdAt: new Date("2024-10-02"),
  },
]

export const mockBookings: Booking[] = [
  {
    id: "b1",
    clientId: "client1",
    barbershopId: "1",
    serviceId: "s1",
    date: new Date("2025-01-20"),
    time: "10:00",
    status: "confirmed",
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "b2",
    clientId: "client2",
    barbershopId: "1",
    serviceId: "s3",
    date: new Date("2025-01-20"),
    time: "14:00",
    status: "confirmed",
    createdAt: new Date("2025-01-14"),
  },
  {
    id: "b3",
    clientId: "client3",
    barbershopId: "1",
    serviceId: "s2",
    date: new Date("2025-01-21"),
    time: "09:00",
    status: "pending",
    createdAt: new Date("2025-01-16"),
  },
  {
    id: "b4",
    clientId: "client4",
    barbershopId: "1",
    serviceId: "s1",
    date: new Date("2025-01-18"),
    time: "15:00",
    status: "completed",
    createdAt: new Date("2025-01-10"),
  },
  {
    id: "b5",
    clientId: "client5",
    barbershopId: "1",
    serviceId: "s3",
    date: new Date("2025-01-19"),
    time: "11:00",
    status: "completed",
    createdAt: new Date("2025-01-12"),
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "e1",
    userId: "user1",
    barbershopId: "1",
    role: "owner",
    name: "Carlos Barbeiro",
    email: "carlos@barbeariaclassica.com",
    avatar: "/placeholder.svg?height=40&width=40",
    phone: "(32) 98765-4321",
    joinedAt: new Date("2024-01-15"),
    permissions: {
      manageBookings: true,
      manageServices: true,
      manageEmployees: true,
      viewReports: true,
    },
  },
  {
    id: "e2",
    userId: "user2",
    barbershopId: "1",
    role: "barber",
    name: "João Cortador",
    email: "joao@barbeariaclassica.com",
    avatar: "/placeholder.svg?height=40&width=40",
    phone: "(32) 97654-3210",
    joinedAt: new Date("2024-02-01"),
    permissions: {
      manageBookings: true,
      manageServices: false,
      manageEmployees: false,
      viewReports: false,
    },
  },
  {
    id: "e3",
    userId: "user3",
    barbershopId: "1",
    role: "receptionist",
    name: "Maria Recepcionista",
    email: "maria@barbeariaclassica.com",
    avatar: "/placeholder.svg?height=40&width=40",
    phone: "(32) 96543-2109",
    joinedAt: new Date("2024-03-15"),
    permissions: {
      manageBookings: true,
      manageServices: false,
      manageEmployees: false,
      viewReports: false,
    },
  },
]

export const mockPlatformStats: PlatformStats = {
  totalBarbershops: 3,
  totalUsers: 150,
  totalBookings: 450,
  totalRevenue: 25000,
  activeBarbershops: 3,
  pendingApprovals: 2,
}
